language: java
jdk:
  - openjdk11

branches:
  only:
    - master
# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

before_install:
  - chmod +x gradlew
# CodeDeploy는 Jar파일을 인식하지 못하므로 Jar+ 기타 설정 파일들을 모아 압축한다.
before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-webserver-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    # 앞에서 생성한 deploy 디렉토리 지정, 해당 위치의 파일들만 S3로 전송
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - donup088@gmail.com